# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: salva.io blog
email: s@salva.io
description: > # this means to ignore newlines until "baseurl:"
  blog para liberarte.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://salva.io/blog/" # the base hostname & protocol for your site
twitter_username: salvitter
github_username:  salvagit

# Build settings
markdown: kramdown

utterson_deploy:
  production:
    url: http://salva.io/blog/
    confirm: true
    description: Production environment
    commands:
    - jekyll build
    - git push
