# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: salvadorp blog
email: s@salvadorp.com
description: > # this means to ignore newlines until "baseurl:"
  blog para liberarte.
baseurl: "http://salvagit.github.io/blog" # the subpath of your site, e.g. /blog
url: "http://salvadorp.com" # the base hostname & protocol for your site
twitter_username: salvitter
github_username:  salvagit

# Build settings
markdown: kramdown
